name: PRODUCT_ID
display_name: Product ID
description: The product the review was for
created_at: '2025-08-28T14:03:17.837742Z'
active: true
visibility_type: normal
table_id:
- Sample Database
- PUBLIC
- REVIEWS
database_type: INTEGER
base_type: type/Integer
effective_type: type/Integer
semantic_type: type/FK
database_is_auto_increment: false
database_required: false
fk_target_field_id:
- Sample Database
- PUBLIC
- PRODUCTS
- ID
dimensions: []
json_unfolding: false
parent_id: null
coercion_strategy: null
preview_display: true
position: 1
custom_position: 0
database_position: 1
has_field_values: null
settings: null
caveats: null
points_of_interest: null
nfc_path: null
serdes/meta:
- id: Sample Database
  model: Database
- id: PUBLIC
  model: Schema
- id: REVIEWS
  model: Table
- id: PRODUCT_ID
  model: Field
database_indexed: null
database_partitioned: null
