name: schema
display_name: Schema
description: name of the schema of the table being referenced
created_at: '2025-08-28T14:03:21.54844Z'
active: true
visibility_type: normal
table_id:
- AppDB
- public
- query_table
database_type: varchar
base_type: type/Text
effective_type: type/Text
semantic_type: null
database_is_auto_increment: false
database_required: false
fk_target_field_id: null
dimensions: []
json_unfolding: false
parent_id: null
coercion_strategy: null
preview_display: true
position: 4
custom_position: 0
database_position: 4
has_field_values: auto-list
settings: null
caveats: null
points_of_interest: null
nfc_path: null
serdes/meta:
- id: AppDB
  model: Database
- id: public
  model: Schema
- id: query_table
  model: Table
- id: schema
  model: Field
database_indexed: null
database_partitioned: null
