name: schema
display_name: Schema
description: null
created_at: '2025-08-28T14:03:21.017749Z'
active: true
visibility_type: normal
table_id:
- AppDB
- public
- metabase_table
database_type: varchar
base_type: type/Text
effective_type: type/Text
semantic_type: type/Category
database_is_auto_increment: false
database_required: false
fk_target_field_id: null
dimensions: []
json_unfolding: false
parent_id: null
coercion_strategy: null
preview_display: true
position: 10
custom_position: 0
database_position: 10
has_field_values: auto-list
settings: null
caveats: null
points_of_interest: null
nfc_path: null
serdes/meta:
- id: AppDB
  model: Database
- id: public
  model: Schema
- id: metabase_table
  model: Table
- id: schema
  model: Field
database_indexed: null
database_partitioned: null
