name: metabase_field_user_settings
display_name: Metabase Field User Settings
description: Mirror table of metabase_field to keep track of user-set values (only settable fields are mirrored)
created_at: '2025-08-28T14:03:19.404288Z'
db_id: AppDB
schema: public
entity_type: entity/GenericTable
active: true
is_upload: false
field_order: database
visibility_type: null
show_in_getting_started: false
initial_sync_status: complete
points_of_interest: null
caveats: null
serdes/meta:
- id: AppDB
  model: Database
- id: public
  model: Schema
- id: metabase_field_user_settings
  model: Table
archived_at: null
data_authority: unconfigured
database_require_filter: null
deactivated_at: null
is_writable: true
