name: product_id
display_name: Product ID
description: The product the review was for
created_at: '2025-08-29T15:30:25.521262Z'
active: true
visibility_type: normal
table_id:
- Postgres 13
- public
- reviews
database_type: int4
base_type: type/Integer
effective_type: type/Integer
semantic_type: type/FK
database_is_auto_increment: false
database_required: false
fk_target_field_id:
- Postgres 13
- public
- products
- id
dimensions: []
json_unfolding: false
parent_id: null
coercion_strategy: null
preview_display: true
position: 1
custom_position: 0
database_position: 1
has_field_values: null
settings: null
caveats: null
points_of_interest: null
nfc_path: null
serdes/meta:
- id: Postgres 13
  model: Database
- id: public
  model: Schema
- id: reviews
  model: Table
- id: product_id
  model: Field
database_indexed: null
database_partitioned: null
