name: products
display_name: Products
description: This is our product catalog. It includes all products ever sold by the Sample Company.
created_at: '2025-08-29T15:30:23.110443Z'
db_id: Postgres 13
schema: public
entity_type: entity/ProductTable
active: true
is_upload: false
field_order: database
visibility_type: null
show_in_getting_started: false
initial_sync_status: complete
points_of_interest: null
caveats: null
serdes/meta:
- id: Postgres 13
  model: Database
- id: public
  model: Schema
- id: products
  model: Table
archived_at: null
data_authority: unconfigured
database_require_filter: null
deactivated_at: null
is_writable: true
